services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: sodybu_db
      POSTGRES_USER: sodyba
      POSTGRES_PASSWORD: sodyba123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
